version: '3'

services:
  broker: # Name of service
    build:
      context: ./../broker # broker source code from this $pwd
      dockerfile: ./../broker/broker.dockerfile # source of dockerfile from this $pwd
    restart: always
    ports:
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 1

  authentication-service:
    depends_on:
      - postgres
    build:
      context: ./../authentication-service
      dockerfile: ./../authentication-service/authentication-service.dockerfile
    restart: always
    ports:
      - "8081:80"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      PG_HOST: "postgres"
      PG_PORT: "5432"
      PG_USER: "postgres"
      PG_PASSWORD: "password"
      PG_DATABASE: "users"
      PG_POOLSIZE: "50"

  postgres:
    image: "postgres:14.2"
    ports:
      - "5437:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/